# Generated by Django 4.1.2 on 2022-10-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='TLWUixB6aa1qWot7', max_length=16, verbose_name='密钥'),
        ),
    ]
